const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(__dirname+'/index.html','utf8');let script=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].map(x=>x[1]).join('\n');script=script.slice(0,script.lastIndexOf('    readCache();'));
const nodes={},storage=new Map(),alerts=[];let open=false;
function node(id){return nodes[id]??=( {innerHTML:'',textContent:'',value:'',style:{},children:[],classList:{add(){},remove(){},toggle(){}},addEventListener(){},querySelector(){return node(id+'-label')}});}
const context={console,URL,Map,Set,Date,Math,JSON,Promise,setTimeout:f=>f(),clearTimeout(){},alert:m=>alerts.push(m),navigator:{},history:{replaceState(){}},window:{location:{href:'https://top10tees.netlify.app/?city=boston'}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},document:{getElementById:node,querySelectorAll:()=>[],querySelector:()=>open?{}:null,addEventListener(){},body:{style:{}},head:{appendChild(){}}}};vm.createContext(context);vm.runInContext(script,context);const run=x=>vm.runInContext(x,context);let count=0;function check(name,fn){fn();count++;console.log('PASS '+name)}
run(`current=PRODUCTS[0];current.inventory={Black:{L:3}};current.colors=['Black','White'];selection={garment:'Tee',color:'Black',size:'L',qty:2,prints:['Back Print']};renderProductModal=()=>{};openCart=()=>{};`);
check('base, extra print, and quantity pricing',()=>assert.equal(run('productTotal()'),80));
check('large size surcharge',()=>{run(`selection.size='4XL'`);assert.equal(run('productTotal()'),90);run(`selection.size='L'`)});
check('partial inventory keeps untracked sizes available',()=>assert.equal(run(`colorStock(current,'Black')`),Infinity));
check('cart add and stock limit across repeated additions',()=>{run('addToBag()');assert.equal(run('cart.length'),1);run('addToBag()');assert.equal(run('cart.length'),1);assert.equal(run('selection.qty'),1)});
check('cart print choices copied independently',()=>{run(`selection.prints.push('Left Sleeve')`);assert.equal(run('cart[0].prints.length'),1)});
check('free shipping and pickup totals',()=>{run(`cart[0].total=100;deliveryMethod='shipping'`);assert.equal(run('shippingFee()'),0);run(`cart[0].total=80;deliveryMethod='pickup'`);assert.equal(run('shippingFee()'),0);run(`deliveryMethod='shipping'`);assert.equal(run('shippingFee()'),10)});
check('percentage and fixed discount caps',()=>{run(`appliedDiscount={type:'percent',value:10}`);assert.equal(run('discountAmount()'),8);run(`appliedDiscount={type:'fixed',value:500}`);assert.equal(run('discountAmount()'),80);run('appliedDiscount=null')});
check('discount refresh preserves buyer fields',()=>{node('buyer-name').value='Test Customer';node('buyer-address').value='Address';run(`discountCodes=[{code:'TOP10TEST',type:'percent',value:10,active:true}];document.getElementById('checkout-discount-input').value='TOP10TEST';applyDiscountCode('checkout-discount-input','checkout-discount-msg')`);assert.equal(node('buyer-name').value,'Test Customer');assert.equal(node('buyer-address').value,'Address')});
check('bag saved and restored with current prices',()=>{run(`saveBag();cart=[];current.price=35;restoreBag()`);assert.equal(run('cart.length'),1);assert.equal(run('cart[0].total'),90)});
check('restored bag rejects sold-out inventory',()=>{run(`current.inventory.Black.L=0;restoreBag()`);assert.equal(run('cart.length'),0);run('current.inventory.Black.L=3')});
check('malformed bag safely discarded',()=>{storage.set('t10t_saved_bag_v1','broken');run('restoreBag()');assert.equal(run('cart.length'),0)});
check('nested modal keeps scrolling locked',()=>{open=true;run(`closeOverlay('zoom-overlay')`);assert.equal(context.document.body.style.overflow,'hidden');open=false;run(`closeOverlay('cart-overlay')`);assert.equal(context.document.body.style.overflow,'')});
check('all admin views render',()=>{run(`manageUnlocked=true`);for(const view of ['designs','inventory','gallery','shipping','wholesale','hoodies','discounts']){run(`manageView='${view}';renderManageBody()`);assert.ok(node('manage-body').innerHTML.length>100)}});
check('both cities render ten designs',()=>{for(const city of ['boston','detroit']){run(`currentCity='${city}';renderProducts()`);assert.equal((node('product-grid').innerHTML.match(/class="product-card /g)||[]).length,10)}});
check('gallery selection previews and queues upload',()=>{run(`gallery=[{id:'gtest',name:'Test Gallery',dataUrl:'data:image/png;base64,AAA'}];openQuickTee(PRODUCTS[0].id);openQuickGallery(PRODUCTS[0].id);quickGalleryPhoto(PRODUCTS[0].id,'gtest')`);assert.equal(node('quick-main-preview').src,'data:image/png;base64,AAA');assert.equal(run('pendingTeePhotos.size'),1)});
check('wholesale tier boundaries',()=>{assert.equal(run('wholesaleTierFor(11)'),null);assert.equal(run('wholesaleTierFor(12).price'),27);assert.equal(run('wholesaleTierFor(48).price'),20)});
check('buyer validation rejects invalid email and missing shipping address',()=>{node('buyer-name').value='Test';node('buyer-phone').value='123';node('buyer-email').value='bad';node('buyer-address').value='';run(`deliveryMethod='shipping'`);assert.equal(run('validBuyer()'),false);node('buyer-email').value='test@example.com';run(`deliveryMethod='pickup'`);assert.equal(run('validBuyer()'),true)});
check('settings save preserves newer changes from another editor',()=>{const value=run(`mergeSettingsChanges({prices:{a:32,b:40},names:{a:'New'}},{prices:{a:30,b:45},names:{a:'Old'}},{prices:{a:30,b:40},names:{a:'Old'}})`);assert.equal(value.prices.a,32);assert.equal(value.prices.b,45);assert.equal(value.names.a,'New')});
check('settings merge supports clearing inventory',()=>{assert.equal(run(`Object.hasOwn(mergeSettingsChanges({L:3,M:5},{M:5},{L:3,M:5}),'L')`),false)});
console.log(`${count} regression checks passed`);
